# Generated by Django 4.2.4 on 2023-08-05 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materials',
            name='created_at',
            field=models.DateField(blank=True, null=True, verbose_name='дата создания'),
        ),
        migrations.AlterField(
            model_name='materials',
            name='is_published',
            field=models.BooleanField(blank=True, default=True, null=True, verbose_name='опубликовано'),
        ),
        migrations.AlterField(
            model_name='materials',
            name='slug',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='slug'),
        ),
        migrations.AlterField(
            model_name='materials',
            name='views_count',
            field=models.IntegerField(default=0, verbose_name='просмоторы'),
        ),
    ]
