# Generated by Django 4.2.4 on 2023-08-07 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_materials_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materials',
            name='is_published',
            field=models.BooleanField(default=True, verbose_name='опубликовано'),
        ),
    ]
